stages:
  - build
  - unit_test
  - push
  - containerize_for_staging
  - test_staged
  - containerize_for_production
  - test_production

variables:
  PROJECT_GROUP: chowtown-cms
  SERVICE_NAME: client
  PRODUCTION_VERSION: "1.0.0"

cache:
  - key:
      files:
          - package-lock.json
    paths:
      - node_modules/

build app:
  except:
    - main
    - staging
  image: node:18-alpine
  stage: build
  script:
    - npm ci
    - npm run lint
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

unit test app:
  except:
    - main
    - staging
  image: node:18-alpine
  stage: unit_test
  script:
    - npm run test

push to staging:
  except:
    - main
    - staging
  stage: push
  script:
    - git config user.email "$GITLAB_ACCOUNT_NAME@gmail.com"
    - git config user.name "$GITLAB_ACCOUNT_NAME"
    - git remote remove origin
    - git remote add origin https://oauth2:$WRITE_TOKEN@gitlab.com/$GITLAB_ACCOUNT_NAME/$PROJECT_GROUP-$SERVICE_NAME.git
    - git branch staging
    - git push -f origin staging

.containerize:
  image: google/cloud-sdk:alpine
  before_script:
    # file variable
    - cat $GCP_CLOUD_BUILD_SERVICE_KEY > /tmp/gcloud-service-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-service-key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud builds submit . --config=cloudbuild.yml --substitutions _PORT=$PORT,_GCP_PROJECT_ID=$GCP_PROJECT_ID,_SERVICE_NAME=$SERVICE_NAME,_IMAGE_V=$IMAGE_V,_VITE_APP_API_URL=$VITE_APP_API_URL,_VITE_AUTH0_CLIENT_ID=$VITE_AUTH0_CLIENT_ID,_VITE_AUTH0_REDIRECT_URI=$VITE_AUTH0_REDIRECT_URI,_VITE_AUTH0_AUDIENCE=$VITE_AUTH0_AUDIENCE,_VITE_AUTH0_DOMAIN=$VITE_AUTH0_DOMAIN
  after_script:
    - rm /tmp/gcloud-service-key.json

containerize for staging:
  only:
    - staging
  stage: containerize_for_staging
  variables:
    IMAGE_V: "staging"
  extends:
    - .containerize
  script:
    - echo

.cypress_tests:
  image: cypress/base:20.5.0
  script:
    - git clone https://oauth2:$WRITE_TOKEN@gitlab.com/$GITLAB_ACCOUNT_NAME/$PROJECT_GROUP-tests.git cypress
    - cd cypress
    - npm install
    - cat $CYPRESS_ENV_JSON > cypress.env.json
    - npm run cypress:run
  after_script:
    - rm cypress.env.json

test staging app:
  only:
    - staging
  stage: test_staged
  environment: staging
  extends: .cypress_tests

containerize for production:
  only:
    - main
  stage: containerize_for_production
  variables:
    IMAGE_V: production
  extends:
    - .containerize
  script:
    - echo

test production app:
  only:
    - main
  stage: test_production
  environment: production
  extends: .cypress_tests
