steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', 'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V',
      '--build-arg', 'VITE_APP_API_URL=$_VITE_APP_API_URL',
      '--build-arg', 'VITE_AUTH0_CLIENT_ID=$_VITE_AUTH0_CLIENT_ID',
      '--build-arg', 'VITE_AUTH0_REDIRECT_URI=$_VITE_AUTH0_REDIRECT_URI',
      '--build-arg', 'VITE_AUTH0_DOMAIN=$_VITE_AUTH0_DOMAIN',
      '--build-arg', 'VITE_AUTH0_AUDIENCE=$_VITE_AUTH0_AUDIENCE',
      '.'
    ]
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V']
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME-$_IMAGE_V',
      '--image',
      'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--port=$_PORT',
      '--allow-unauthenticated',
    ]
